title: Rafael Santos - GitHub Pages

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      pagination:
        enabled: true
        per_page: 10
        sort_field: "name"
        sort_reverse: false
